
// Image Generation Constants
const MAX_WIDTH = 2048;
const MAX_HEIGHT = 2048;
const MIN_WIDTH = 256;
const MIN_HEIGHT = 256;
const MAX_PROMPT_LENGTH = 10000;

// Rate Limiting Constants
const USER_DAILY_LIMIT = parseInt(process.env.RATE_LIMIT_USER_DAILY || '20', 10);
const ADMIN_DAILY_LIMIT = parseInt(process.env.RATE_LIMIT_ADMIN_DAILY || '200', 10);

// Cache Constants
const PRESIGNED_S3_URL_EXPIRATION = 900; // 15 minutes in seconds
const URL_CACHE_TTL = PRESIGNED_S3_URL_EXPIRATION;
const METADATA_CACHE_TTL = 86400; // 24 hours in seconds

// Custom Style Prompt Constants
const MAX_CUSTOM_STYLE_PROMPT_LENGTH = 2000;
const MAX_CUSTOM_STYLE_PROMPTS_PER_USER = 50;


export {
  MAX_WIDTH,
  MAX_HEIGHT,
  MIN_WIDTH,
  MIN_HEIGHT,
  MAX_PROMPT_LENGTH,
  URL_CACHE_TTL,
  PRESIGNED_S3_URL_EXPIRATION,
  METADATA_CACHE_TTL,
  MAX_CUSTOM_STYLE_PROMPT_LENGTH,
  MAX_CUSTOM_STYLE_PROMPTS_PER_USER,
  USER_DAILY_LIMIT,
  ADMIN_DAILY_LIMIT
};
