export const LOGIN_SECURITY = {
  ATTEMPTS_BEFORE_WARNING: 3,
  ATTEMPTS_BEFORE_LOCKOUT: 7,
  LOCKOUT_DURATION_MS: 15 * 60 * 1000,
};

export const ACCOUNT_DELETION = {
  GRACE_PERIOD_DAYS: 14,
  GRACE_PERIOD_MS: 14 * 24 * 60 * 60 * 1000,
};
